import {Product} from '@prisma/client'
import Head from 'next/head'
import Image from 'next/image'
import ProductCard from '../component/productsCard'
import styles from '../styles/Home.module.css'
import prisma from './../db'

export async function getServerSideProps() {
  try {
    const products = await prisma.product.findMany();
    return {
      props: { products },
    };
  } catch (err) {
    return {
      props: { products: [] },
    };
  }
}


export type ProductWithReviewCount = Product & { _count: { reviews: number } };

interface HomeProps {
  products: ProductWithReviewCount[];
}

export default function Home(props: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          {/* <a href="https://nextjs.org/learn" className={styles.card}> */}
            {props.products.map((p, i: number) => (
              <ProductCard product={p} key={i} />
            ))}
          {/* </a> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
